zlib.output_compression = On
zlib.output_compression_level = 5
upload_max_filesize = 16M
post_max_size = 16M
max_execution_time = 300
memory_limit = 256M
display_errors = On
log_errors = On
error_log = error_log
